### PR TITLE
Ran go mod tidy

### PR DESCRIPTION
**Pull request by bvdwalt**
Running `go mod tidy` as per #73

### CODE REVIEW

**Review by malukenho — APPROVED** [review]

**Comment by malukenho** [comment]
Nicely done! I think we should add it to the CI as well.

**Comment by bvdwalt** [comment]
I added a step to the CI yaml as well. Hopefully that works fine. 

I see the codecov step failed in the CI pipeline earlier, seems to be complaining about the token in use.

**Comment by malukenho** [comment]
Thank you @bvdwalt

**Comment by bvdwalt** [comment]
Only a pleasure @malukenh. Have a great day.

**Pull request merged**
