### PR TITLE
Add formatting mechanism & Revive setup locally

### PR DESCRIPTION
**Pull request by agustingomes**
The mechanism relies of the `go fmt` mechanism, which applies some formatting to the source files.

The github action image does not read the local configuration, this change allows the dependency to be installed in the path defined in `GOPATH` environment variable.

This validates that Go is installed locally. The absence of those variables is an indication Go is eithe rnot installed in the system or not properly configured.

### CODE REVIEW

**Comment by EHER** [comment]
I will rebase the branch.

**Comment by EHER** [comment]
Done.

**Review by EHER — APPROVED** [review]

**Comment by agustingomes** [comment]
I'll do another rebase, GitHub is failing to merge them because of some signature 🤷🏼‍♂️

**Comment by EHER** [comment]
Not sure why but it was fine for me.

**Pull request merged**
